version: '3.8'

services:
  # PostgresSQL Database Service
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sms
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

  # Redis Database
  redis-db:
    container_name: redis-db
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network

  # Eureka Discovery Service
  eureka-discovery:
    container_name: eureka-discovery
    build:
      context: ./eureka-discovery
      dockerfile: Dockerfile
    hostname: eureka
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - EUREKA_INSTANCE_HOSTNAME=eureka-discovery
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    ports:
      - "8761:8761"
    depends_on:
      - postgres-db
    networks:
      - my-network

  # API Gateway Service
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      - eureka-discovery
    ports:
      - "8060:8060"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-discovery:8761/eureka
      - USERS_SERVICE_HOST=http://users:8080
      - AUTH_SERVICE_HOST=http://auth:8070
    networks:
      - my-network

  # Users Service
  users:
    container_name: users
    build:
      context: ./users
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
      - redis-db
      - eureka-discovery
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/sms?createDatabaseIfNotExist=true
      - SPRING_DATA_REDIS_HOST=redis-db
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - my-network

  # Auth Service
  auth:
    container_name: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
      - eureka-discovery
      - users
    ports:
      - "8070:8070"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/sms?createDatabaseIfNotExist=true
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - my-network

networks:
  my-network:
    external: true

volumes:
  postgres-data:
